# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainImage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from repo.behaviors import Service

name_dic = {}
room_number_dic = {}
room_result_dic = {}
priority_number = 0

class Ui_MainWindow(object):
    def __init__(self):
        self.serviceClass = Service(room_number_dic,room_result_dic,priority_number)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1091, 896)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1091, 871))
        self.tabWidget.setWhatsThis("")
        self.tabWidget.setObjectName("tabWidget")
        self.setting = QtWidgets.QWidget()
        self.setting.setObjectName("setting")
        self.submit = QtWidgets.QPushButton(self.setting)
        self.submit.setGeometry(QtCore.QRect(340, 720, 141, 21))
        self.submit.setObjectName("submit")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.setting)
        self.textBrowser_3.setGeometry(QtCore.QRect(170, 90, 711, 111))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.roomListBox = QtWidgets.QTextEdit(self.setting)
        self.roomListBox.setGeometry(QtCore.QRect(490, 360, 391, 351))
        self.roomListBox.setObjectName("roomListBox")
        self.roomExplain = QtWidgets.QTextBrowser(self.setting)
        self.roomExplain.setGeometry(QtCore.QRect(490, 210, 391, 141))
        self.roomExplain.setObjectName("roomExplain")
        self.reset = QtWidgets.QPushButton(self.setting)
        self.reset.setGeometry(QtCore.QRect(490, 720, 131, 21))
        self.reset.setObjectName("reset")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.setting)
        self.textBrowser_2.setGeometry(QtCore.QRect(170, 40, 711, 41))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.nameListBox = QtWidgets.QTextEdit(self.setting)
        self.nameListBox.setGeometry(QtCore.QRect(170, 360, 311, 351))
        self.nameListBox.setObjectName("nameListBox")
        self.textBrowser = QtWidgets.QTextBrowser(self.setting)
        self.textBrowser.setGeometry(QtCore.QRect(640, 720, 251, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.nameExplain = QtWidgets.QTextBrowser(self.setting)
        self.nameExplain.setGeometry(QtCore.QRect(170, 210, 311, 141))
        self.nameExplain.setObjectName("nameExplain")
        self.scoreNumber = QtWidgets.QSpinBox(self.setting)
        self.scoreNumber.setGeometry(QtCore.QRect(110, 360, 51, 41))
        self.scoreNumber.setObjectName("scoreNumber")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.setting)
        self.textBrowser_7.setGeometry(QtCore.QRect(80, 320, 81, 31))
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.tabWidget.addTab(self.setting, "")
        self.result = QtWidgets.QWidget()
        self.result.setObjectName("result")
        self.resultBox = QtWidgets.QTextBrowser(self.result)
        self.resultBox.setGeometry(QtCore.QRect(190, 61, 691, 741))
        self.resultBox.setObjectName("resultBox")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.result)
        self.textBrowser_8.setGeometry(QtCore.QRect(190, 10, 681, 41))
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.tabWidget.addTab(self.result, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.submit.clicked.connect(self.submitButtonClicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.submit.setText(_translate("MainWindow", "제출"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">해당 프로그램은 순위에 맞춰 팀을 배정해주는 프로그램입니다.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">팀에 제한된 인원이 있고 1순위 먼저 배정됩니다.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">해당 팀을 지원했을 때 인원이 초과되면 랜덤으로 투표됩니다.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">배정받지 못한 인원은 그 다음 순위로 다시 배정됩니다.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">동일하게 인원 초과시 랜덤으로 배정됩니다.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">같은방식으로 모든 인원이 배정된 후 결과가 나옵니다.</p></body></html>"))
        self.roomExplain.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">방탈출 이름과 인원을 적어주세요</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ex) </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">전래동 4</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">링 3</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">포레스트 3</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- 방탈출 이름은 띄어쓰기 한단어여야 합니다.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- 방탈출 이름과 사람이 적은 방탈출 순위 이름이 동일해야 합니다.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.reset.setText(_translate("MainWindow", "리셋"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">순위 기반 팀 배정 프로그램</span></p></body></html>"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Made By Jiwon Kim(ESA Team)</span></p></body></html>"))
        self.nameExplain.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">투표자 성함과 순위를 띄어쓰기로 구분해서 적어주세요</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">순위 개수에 맞게 넣어주세요</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">예시)순위 개수 3개 기준</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">이름 1순위 2순위 3순위</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ex)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">홍길동 전래동 링 포레스트</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">아무개 렛플 하이팜 대호시장</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">강낭콩 링 네모네모 네드</p></body></html>"))
        self.textBrowser_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">순위 개수</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.setting), _translate("MainWindow", "설정"))
        self.textBrowser_8.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">결과</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.result), _translate("MainWindow", "결과"))

    def submitButtonClicked(self):
        self.set_priority_number()
        name_dic = self.set_name_dic()
        room_number_dic = self.set_room_dic()

        if name_dic is None or room_number_dic is None:
            return ""

        result = self.serviceClass.get_result(name_dic, room_number_dic)
        self.writeResult(result)

    def set_name_dic(self):
        text = self.nameListBox.toPlainText()
        name_dic = self.serviceClass.get_name_dic(text)
        if name_dic is None:
            print("asd")

        return name_dic

    def set_room_dic(self):
        text = self.roomListBox.toPlainText()
        room_number_dic = self.serviceClass.get_room_dic(text)
        if room_number_dic is None:
            print("asd")

        return  room_number_dic

    def set_priority_number(self):
        priority_number = self.scoreNumber.value()
        self.serviceClass.set_priority_number(priority_number)

    def writeResult(self, result):
        self.resultBox.setText(result)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
